import streamlit as st
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.models import load_model
from PIL import Image

IMG_SIZE = 224

model = load_model('model_effnet_2.h5')

st.title('Image prediction : Real or AI generated ?')

st.write("Upload an image and the model will tell you if it is real or AI generated.")

uploaded_file = st.file_uploader("Choose an image", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    img = Image.open(uploaded_file)
    st.image(img, caption="Image uploaded", use_column_width=True)

    img = img.resize((IMG_SIZE, IMG_SIZE))  
    img_array = np.array(img)  
    img_array = np.expand_dims(img_array, axis=0)  
    img_array = preprocess_input(img_array) 

    prediction = model.predict(img_array)

    if prediction[0][0] > prediction[0][1]:
        st.write("The image is **IA generated**.")
    else:
        st.write("The image is **real**.")

    st.write(f"The probability of image generated by AI : {prediction[0][0]*100:.2f}%")
    st.write(f"The probability of real image : {prediction[0][1]*100:.2f}%")
